name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          access: "public"
          token: "${{ secrets.NPM_AUTH_TOKEN }}"
